server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wzz-cute/springcloundtest.git
          search-paths:
            - springcloudtest
      label: config-devtest-master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

